- name: Deploy Enterprise Admin Portal Frontend
  hosts: all
  become: True
  gather_facts: True
  vars:
    ENABLE_NEWRELIC: False
    CLUSTER_NAME: 'admin_portal'
    ADMIN_PORTAL_ENABLED: True
    ADMIN_PORTAL_SANDBOX_BUILD: False
  roles:
    - role: admin_portal
      MFE_NAME: admin-portal
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
    - role: newrelic_infrastructure
      when: COMMON_ENABLE_NEWRELIC_INFRASTRUCTURE